version: '3.2'

networks:
  default:
    external:
      name: my_net

services:
  web_one:
    image: cblunt/rails-basic-app
    ports:
      - '3000:3000'
    environment:
      - RAILS_ENV=development
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=my_app_development
    command: /bin/sh -c 'bin/rails db:migrate && bin/rails s -b 0.0.0.0 -P 3000'
